In [13]:
import numpy as np

a = np.array([1, 2])
b = np.array([[1, 2],
              [3, 4]])

# np.dot(b, a)
# [np.linalg.norm(t) for t in b]
np.linalg.norm(b, axis=1) 

array([2.23606798, 5.        ])

In [ ]:


# Tạo DataFrame với mỗi phần tử là một list
temp = pd.DataFrame({'temp': [[1, 2], [3, 4]]})
np.linalg.norm(temp['temp'].tolist(), axis = 1)

array([2.23606798, 5.        ])

In [1]:
import numpy as np
import pandas as pd

temp = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]]
}
temp = pd.DataFrame(temp)
# np.linalg.norm(temp['color_feature'].tolist(), axis = 1)
temp['new'] = temp['class_ID'] + 1

In [18]:
pd.DataFrame(np.array(temp['color_feature'].values.tolist()).reshape(-1, 3))

,0,1,2
0,1,1,1
1,2,2,2
2,3,3,3
3,4,4,4


In [20]:
(temp['class_ID'] + 1).values

array([1, 1, 1, 1])

In [33]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

1 / (a + b)

array([0.25      , 0.16666667])

In [34]:
temp = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]]
}
del temp['class_ID']
temp

{'color_feature': [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]}

In [2]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

a + b

array([4, 6])

In [ ]:
from dataclasses import dataclass, field
from typing import List

@dataclass
class Check:
    Active: bool = False
    Kind: int = 0
    List_Vehicle: List[int] = field(default_factory=lambda: [])
    Angle: List[float] = field(default_factory=lambda: [])

    def __add__(self, other):
        if not isinstance(other, Check):
            return NotImplemented
        return Check(
            Active=self.Active,
            Kind=self.Kind,
            List_Vehicle = self.List_Vehicle + other.List_Vehicle,
            Angle = self.Angle + other.Angle
            )

    def __repr__(self):
        return f"Check({self.Active}, {self.Kind}, {self.List_Vehicle}, {self.Angle})"

ValueError: mutable default <class 'list'> for field List_Vehicle is not allowed: use default_factory

In [ ]:
import numpy as np

# Tạo lưới 2x3 check
row, col = 2, 3
grid = np.array([[Check() for _ in range(col)] for _ in range(row)], dtype=object)

# Tạo check để cộng vào
c = Check(True, 2, [1]*6, [10, 20])

# grid[:, 1] += 1
grid

TypeError: unsupported operand type(s) for +: 'Check' and 'int'

In [26]:
grid = np.array([[[0, 0] for _ in range(col)] for _ in range(row)], dtype=object)
grid[1, :, 1] = 1
grid

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 1],
        [0, 1],
        [0, 1]]], dtype=object)