In [13]:
import numpy as np

a = np.array([1, 2])
b = np.array([[1, 2],
              [3, 4]])

# np.dot(b, a)
# [np.linalg.norm(t) for t in b]
np.linalg.norm(b, axis=1) 

array([2.23606798, 5.        ])

In [ ]:


# Tạo DataFrame với mỗi phần tử là một list
temp = pd.DataFrame({'temp': [[1, 2], [3, 4]]})
np.linalg.norm(temp['temp'].tolist(), axis = 1)

array([2.23606798, 5.        ])

In [6]:
import numpy as np
import pandas as pd

temp = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]]
}
# temp = pd.DataFrame(temp)
# np.linalg.norm(temp['color_feature'].tolist(), axis = 1)
for char in temp.values():
    print(char)

[0, 0, 0, 0]
[[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]


In [18]:
pd.DataFrame(np.array(temp['color_feature'].values.tolist()).reshape(-1, 3))

,0,1,2
0,1,1,1
1,2,2,2
2,3,3,3
3,4,4,4


In [20]:
(temp['class_ID'] + 1).values

array([1, 1, 1, 1])

In [33]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

1 / (a + b)

array([0.25      , 0.16666667])

In [50]:
box_1 = [1, 1, 2, 2]

box = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]],
    'box' : [[1,1,1,1],
            [2,2,2,2],
            [3,3,3,3],
            [4,4,4,4]]
}
# del box['class_ID']
box = np.array(pd.DataFrame(box)['box'].values.tolist()).reshape(-1, 4)
box = pd.DataFrame(box, columns = ['x', 'y', 'h', 'w'])

box['x_min'] = (box['x'] - box['h'] / 2).clip(lower=box_1[0])
box['y_min'] = (box['y'] - box['w'] / 2).clip(lower=box_1[1])
box['x_max'] = (box['x'] + box['h'] / 2).clip(upper=box_1[2])
box['y_max'] = (box['y'] + box['w'] / 2).clip(upper=box_1[3])

box['area'] = box['h'] * box['w']
box['inter_h'] = (box['x_max'] - box['x_min']).clip(lower=0)
box['inter_w'] = (box['y_max'] - box['y_min']).clip(lower=0)

area_match = (box['inter_w'] * box['inter_h']).values
area_total = box['area'].values + 2 - area_match
IOU = area_match / area_total
temp_1 = np.array([i >= 0.7 for i in IOU])
temp_1

array([False, False, False, False])

In [51]:
box = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]],
    'box' : [[1,1,1,1],
            [2,2,2,2],
            [3,3,3,3],
            [4,4,4,4]]
}
box = pd.DataFrame(box)
data = box['color_feature'].tolist()

vec1 = np.array([1, 2, 3])
vec2 = np.array(data)

dot = np.dot(vec2, vec1)
norm1 = np.linalg.norm(vec1)
norm2 = np.linalg.norm(vec2, axis=1)

print(np.where(norm1 * norm2 != 0, dot / (norm1 * norm2), 0))
print()
temp_2 = np.where(norm1 * norm2 != 0, dot / (norm1 * norm2) >= 0.7, False)
print(temp_2)


[0.9258201 0.9258201 0.9258201 0.9258201]

[ True  True  True  True]


In [ ]:
temp_1 & temp_2

array([False, False, False, False])

In [60]:
box = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]],
    'box' : [[1,1,1,1],
            [2,2,2,2],
            [3,3,3,3],
            [4,4,4,4]]
}
print(pd.DataFrame(box)[[True, False, True, False]]['color_feature'].tolist())
print(pd.DataFrame(box)[[True, False, True, False]].reset_index(drop = True))

[[1, 1, 1], [3, 3, 3]]
   class_ID color_feature           box
0         0     [1, 1, 1]  [1, 1, 1, 1]
1         0     [3, 3, 3]  [3, 3, 3, 3]


# temp

In [29]:
from dataclasses import dataclass, field
from typing import List

@dataclass
class Check:
    Active: bool = False
    Kind: int = 0
    List_Vehicle: List[int] = field(default_factory=lambda: [])
    Angle: List[float] = field(default_factory=lambda: [])

    def __add__(self, other):
        if not isinstance(other, Check):
            return NotImplemented
        return Check(
            Active=self.Active,
            Kind=self.Kind,
            List_Vehicle = self.List_Vehicle + other.List_Vehicle,
            Angle = self.Angle + other.Angle
            )

    def __repr__(self):
        return f"Check({self.Active}, {self.Kind}, {self.List_Vehicle}, {self.Angle})"

## temp1

In [32]:
import numpy as np

# Tạo lưới 2x3 check
row, col = 2, 3
grid = np.array([[Check() for _ in range(col)] for _ in range(row)], dtype=object)

# Tạo check để cộng vào
c = Check(True, 2, [1], [10])

grid[:, 1] += c
grid

array([[Check(False, 0, [], []), Check(False, 0, [1], [10]),
        Check(False, 0, [], [])],
       [Check(False, 0, [], []), Check(False, 0, [1], [10]),
        Check(False, 0, [], [])]], dtype=object)

In [26]:
grid = np.array([[[0, 0] for _ in range(col)] for _ in range(row)], dtype=object)
grid[1, :, 1] = 1
grid

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 1],
        [0, 1],
        [0, 1]]], dtype=object)

In [2]:
import os
print(os.listdir())

['Backend.py', 'Charater.py', 'Checker.py', 'DeepSort.py', 'Def_common.py', 'Draw.py', 'FrontEnd.py', 'Map.py', 'Process_OutPut.py', 'test.ipynb', '__pycache__']


In [3]:
from ultralytics import YOLO
import cv2

# Load mô hình .pt
model = YOLO("./final.pt")

img = cv2.imread('./img_1.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

result = model(img)


0: 384x640 4 xe_mays, 1 o_to, 77.8ms
Speed: 4.3ms preprocess, 77.8ms inference, 5.6ms postprocess per image at shape (1, 3, 384, 640)


In [15]:
result[0].boxes[0].xywh[0]

tensor([306.7487, 247.8339,  21.0904,  42.5434])

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("YOLOBroadcast").getOrCreate()
sc = spark.sparkContext

# Broadcast trọng số
# broadcast_weights = sc.broadcast(weights)


In [ ]:
from ultralytics import YOLO
import torch

def run_inference_on_partition(partition):
    # Load mô hình YOLO trống (cùng loại với best.pt)
    model = YOLO("yolov8n.pt")  # hoặc đúng backbone bạn đang dùng
    model.model.load_state_dict(broadcast_weights.value)
    model.eval()

    for record in partition:
        # Giả sử record là đường dẫn ảnh
        results = model(record)
        yield results[0].tojson()  # hoặc .boxes, .probs tuỳ bạn


In [44]:
from dataclasses import dataclass, field
from typing import List

@dataclass
class Char:
    class_id: int = 0
    HSV: List[int] = field(default_factory=lambda: [])
    box: List[int] = field(default_factory=lambda: [])

In [61]:
def CheckColorFeature(self, data, ratio, return_score = False):
    vec1 = np.array(self.Color_Feature)
    vec2 = np.array(data)

    dot = np.dot(vec2, vec1)
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2, axis=1)
    
    if return_score:
        temp = np.where(norm1 * norm2 != 0, dot / (norm1 * norm2), 0)
        return temp
    return np.where(norm1 * norm2 != 0, dot / (norm1 * norm2) >= ratio, False)

In [65]:
import pandas as pd

box = {
    'class_ID' : [0],
    'color_feature' : [[1,1,1]],
    'box' : [[1,1,1,1]]
}
print(pd.DataFrame(box)['color_feature'].values.tolist()[0])

[1, 1, 1]
