In [13]:
import numpy as np

a = np.array([1, 2])
b = np.array([[1, 2],
              [3, 4]])

# np.dot(b, a)
# [np.linalg.norm(t) for t in b]
np.linalg.norm(b, axis=1) 

array([2.23606798, 5.        ])

In [ ]:


# Tạo DataFrame với mỗi phần tử là một list
temp = pd.DataFrame({'temp': [[1, 2], [3, 4]]})
np.linalg.norm(temp['temp'].tolist(), axis = 1)

array([2.23606798, 5.        ])

In [1]:
import numpy as np
import pandas as pd

temp = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]]
}
temp = pd.DataFrame(temp)
# np.linalg.norm(temp['color_feature'].tolist(), axis = 1)
temp['new'] = temp['class_ID'] + 1

In [18]:
pd.DataFrame(np.array(temp['color_feature'].values.tolist()).reshape(-1, 3))

,0,1,2
0,1,1,1
1,2,2,2
2,3,3,3
3,4,4,4


In [20]:
(temp['class_ID'] + 1).values

array([1, 1, 1, 1])

In [33]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

1 / (a + b)

array([0.25      , 0.16666667])

In [ ]:
temp = {
    'class_ID' : [0, 0, 0, 0],
    'color_feature' : [[1,1,1],
                       [2,2,2],
                       [3,3,3],
                       [4,4,4]]
}
del temp['class_ID']